// cl: /O1 /DNDEBUG /DWIN32 /D_WINDOWS /MD /EHsc
// ?DoesCommandRequireACommandID@@YAHW4NetCommandType@@@Z, retail 0x005811B5, 116 bytes.
// BFME2's DoesCommandRequireACommandID: takes NetCommandType by value (mov eax,[esp+4]),
// returns Int (xor eax,eax / inc eax, whole register, not Bool). Identity proven by
// 30+ callers (0x004CF890, 0x004CFDE1, 0x004D0445 and 27 unblocked) that push
// [esi+0x14] (NetCommandMsg m_commandType) and test al, then call GenerateNextCommandID
// at 0x005811A8 and store ax into [esi+0x10] (m_id) -- the ZH/BFME1
// if (DoesCommandRequireACommandID(type)) setID(GenerateNextCommandID()) pattern.
// Donor is BFME1 Code/GameEngine/Source/GameNetwork/NetworkUtil.cpp
// (DoesCommandRequireACommandID, same Int return); BFME2's list has 21 types in
// retail order read off the chain: 4,5,6,3,10,8,9,7,11,14,27,16,17,18,20,19,21,22,26,28,30
// (FILEANNOUNCE before FILE, DISCONNECTFRAME early, 22 unnamed and 30 MAX added,
// DISCONNECTPLAYER 25 dropped vs BFME1's 20).
typedef int Int;
enum NetCommandType
{
	NETCOMMANDTYPE_FRAMEINFO = 3,
	NETCOMMANDTYPE_GAMECOMMAND = 4,
	NETCOMMANDTYPE_REQUEST_GAMESPY_STATS_AUTHKEY = 5,
	NETCOMMANDTYPE_GAMESPY_STATS_AUTHKEY = 6,
	NETCOMMANDTYPE_REQUESTPLAYERLEAVE = 7,
	NETCOMMANDTYPE_INFORMPLAYERLEAVEFRAME = 8,
	NETCOMMANDTYPE_REQUESTFRAMEDATA = 9,
	NETCOMMANDTYPE_PLAYERLEAVE = 10,
	NETCOMMANDTYPE_DESTROYPLAYER = 11,
	NETCOMMANDTYPE_CHAT = 14,
	NETCOMMANDTYPE_LOADCOMPLETE = 16,
	NETCOMMANDTYPE_TIMEOUTSTART = 17,
	NETCOMMANDTYPE_WRAPPER = 18,
	NETCOMMANDTYPE_FILE = 19,
	NETCOMMANDTYPE_FILEANNOUNCE = 20,
	NETCOMMANDTYPE_FILEPROGRESS = 21,
	NETCOMMANDTYPE_DISCONNECTVOTE = 26,
	NETCOMMANDTYPE_DISCONNECTFRAME = 27,
	NETCOMMANDTYPE_DISCONNECTSCREENOFF = 28
};
Int DoesCommandRequireACommandID(NetCommandType type)
{
	if ((type == NETCOMMANDTYPE_GAMECOMMAND) ||
		(type == NETCOMMANDTYPE_REQUEST_GAMESPY_STATS_AUTHKEY) ||
		(type == NETCOMMANDTYPE_GAMESPY_STATS_AUTHKEY) ||
		(type == NETCOMMANDTYPE_FRAMEINFO) ||
		(type == NETCOMMANDTYPE_PLAYERLEAVE) ||
		(type == NETCOMMANDTYPE_INFORMPLAYERLEAVEFRAME) ||
		(type == NETCOMMANDTYPE_REQUESTFRAMEDATA) ||
		(type == NETCOMMANDTYPE_REQUESTPLAYERLEAVE) ||
		(type == NETCOMMANDTYPE_DESTROYPLAYER) ||
		(type == NETCOMMANDTYPE_CHAT) ||
		(type == NETCOMMANDTYPE_DISCONNECTFRAME) ||
		(type == NETCOMMANDTYPE_LOADCOMPLETE) ||
		(type == NETCOMMANDTYPE_TIMEOUTSTART) ||
		(type == NETCOMMANDTYPE_WRAPPER) ||
		(type == NETCOMMANDTYPE_FILEANNOUNCE) ||
		(type == NETCOMMANDTYPE_FILE) ||
		(type == NETCOMMANDTYPE_FILEPROGRESS) ||
		(type == (NetCommandType)22) ||
		(type == NETCOMMANDTYPE_DISCONNECTVOTE) ||
		(type == NETCOMMANDTYPE_DISCONNECTSCREENOFF) ||
		(type == (NetCommandType)30))
	{
		return 1;
	}
	return 0;
}
