// cl: /O1 /MD
// Each class redeclares its protected virtual destructor and defines it locally,
// which emits the scalar deleting destructor in this TU; the dtor call inside
// resolves through that destructor's own row (same pattern as spec_gdtor).
// Generated by build/mg/famgen.py (gdtor_prot): same-shape family members.

// ??_GDieModule@@MAEPAXI@Z @0x45cef4
class DieModule { protected: __declspec(noinline) virtual ~DieModule(); private: int m_famgen;
  friend void famgenDelete(DieModule *p); };
DieModule::~DieModule() { m_famgen = 0; }
void famgenDelete(DieModule *p) { delete p; }

// ??_GFireWeaponWhenDeadBehavior@@MAEPAXI@Z @0x460b50
class FireWeaponWhenDeadBehavior { protected: __declspec(noinline) virtual ~FireWeaponWhenDeadBehavior(); private: int m_famgen;
  friend void famgenDelete(FireWeaponWhenDeadBehavior *p); };
FireWeaponWhenDeadBehavior::~FireWeaponWhenDeadBehavior() { m_famgen = 0; }
void famgenDelete(FireWeaponWhenDeadBehavior *p) { delete p; }

