// cl: -EHsc /Os -Ireference/open-bfme-1/game/gen_small
// stlport
// Generated by: python3 tools/gen_small.py gen-tgrid
// Do not edit by hand; regenerate instead.
//
// Each row this file carries is a retail body that IS this instantiation:
// the game links STLport 4.5.3, so a container member's code is the vendor
// template over a payload of that shape, and the payload's name never
// reaches the bytes. The synthetic payloads below are anonymous by design --
// they reproduce a layout and a lifecycle, never a class identity -- and
// every call target is read out of the retail bytes and pinned in
// targets/game/reverse/symbols.csv, so the bytes prove the callee.

#include <deque>
#include <list>
#include <vector>


// 0x001DB910 vec_p4cd
struct Gen_t_001db910_p4cd { int a[1]; Gen_t_001db910_p4cd(); Gen_t_001db910_p4cd(const Gen_t_001db910_p4cd&); ~Gen_t_001db910_p4cd(); Gen_t_001db910_p4cd& operator=(const Gen_t_001db910_p4cd&); };
bool operator==(const Gen_t_001db910_p4cd&, const Gen_t_001db910_p4cd&);
bool operator<(const Gen_t_001db910_p4cd&, const Gen_t_001db910_p4cd&);
template class _STL::vector<Gen_t_001db910_p4cd >;
